config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :students

  root "students#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :todos, dependent: :destroy
	accepts_nested_attributes_for :todos, allow_destroy: true, reject_if: :all_blank
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.todos.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:roll, :name, :student_class, :remarks,
        todos_attributes: [:id, :task, :day])
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:task, :day, :student_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :roll, style: "display: block" %>
    <%= form.number_field :roll %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :student_class, style: "display: block" %>
    <%= form.number_field :student_class %>
  </div>

  <div>
    <%= form.label :remarks, style: "display: block" %>
    <%= form.text_field :remarks %>
  </div>

  <div>
    <%= form.fields_for :todos do |todo| %>
      <%= render 'todo_fields', form: todo %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <td>
    <p>
      <strong>Roll:</strong>
      <%= student.roll %>
    </p>
  </td>

  <td>
    <p>
      <strong>Name:</strong>
      <%= student.name %>
    </p>
  </td>

  <td>
    <p>
      <strong>Class:</strong>
      <%= student.student_class %>
    </p>
  </td>

  <td>
    <p>
      <strong>Remarks:</strong>
      <%= student.remarks %>
    </p>
  </td>

  <td>
    <% student.todos.each do |todo| %>
      <p>
        <strong>Task:</strong>
        <%= todo.task %>
      </p>

      <p>
        <strong>Day:</strong>
        <%= todo.day %>
      </p>
    <% end %>
  </td>

</div>

app/views/students/_todo_fields.html.erb
<div>
  <div>
    <%= form.label :task, style: "display: block" %>
    <%= form.text_field :task %>
  </div>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.number_field :day %>
  </div>

  <%= link_to_remove_association "remove todo", form %>
</div>
  

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Test</h1>

<div id="students">
  <table>
    <% @students.each do |student| %>
    <tr>
        <%= render student %>
      <td>
        <p>
          <%= link_to "Show this student", student %>
        </p>
      </td>
    </tr>

    <% end %>  
  </table>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :task, style: "display: block" %>
    <%= form.text_field :task %>
  </div>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.number_field :day %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Task:</strong>
    <%= todo.task %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= todo.day %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= todo.student_id %>
  </p>

</div>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todos</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <%= render todo %>
    <p>
      <%= link_to "Show this todo", todo %>
    </p>
  <% end %>
</div>

<%= link_to "New todo", new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>